// clang-format off
// 生成物。手で編集しない。python eng/vim-oracle.py --regenerate（Vim 9.1）
// oracle: C:\Program Files\Vim\vim91\vim.exe — VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  3 2024 23:53:58)
// 既定の設定（ADR 0012 の決定 8）: set nocompatible / set backspace=indent,eol,start
// fixtures.json: sha256 b24311a61e7e9d36bf7a3a33eb3f4577744b1bf9d583c2d4a71b5ba9076ddec4 / 256 fixtures
#pragma once

#include "VimFixture.hpp"

#include <array>

namespace nenenib::tests
{
constexpr std::array<VimFixture, 256> vim_fixtures{{
    {"h-at-the-line-start-stays", "alpha", "h", "alpha", 1, 1, "", ""},
    {"h-with-a-count", "alpha", "$3h", "alpha", 1, 2, "", ""},
    {"l-does-not-pass-the-last-character", "abc", "lll", "abc", 1, 3, "", ""},
    {"l-with-a-count-clamps", "hello", "5l", "hello", 1, 5, "", ""},
    {"zero-goes-to-the-line-start", "  abc", "$0", "  abc", 1, 1, "", ""},
    {"dollar-goes-to-the-last-character", "  abc", "$", "  abc", 1, 5, "", ""},
    {"w-crosses-punctuation", "alpha, beta; gamma", "www", "alpha, beta; gamma", 1, 12, "", ""},
    {"w-crosses-the-line", "alpha beta\ngamma", "ww", "alpha beta\ngamma", 2, 1, "", ""},
    {"w-stops-on-the-last-word", "alpha beta", "ww", "alpha beta", 1, 10, "", ""},
    {"w-stops-on-an-empty-line", "abc\n\ndef", "w", "abc\n\ndef", 2, 1, "", ""},
    {"w-with-a-count", "one two three", "2w", "one two three", 1, 9, "", ""},
    {"b-crosses-punctuation", "alpha, beta", "$bb", "alpha, beta", 1, 6, "", ""},
    {"b-crosses-the-line", "abc\ndef", "jb", "abc\ndef", 1, 1, "", ""},
    {"b-at-the-start-of-the-buffer-stays", "abc", "b", "abc", 1, 1, "", ""},
    {"b-with-a-count", "one two three", "$2b", "one two three", 1, 5, "", ""},
    {"j-with-a-count-clamps-to-the-last-line", "one\ntwo", "3j", "one\ntwo", 2, 1, "", ""},
    {"k-with-a-count-clamps-to-the-first-line", "one\ntwo", "j3k", "one\ntwo", 1, 1, "", ""},
    {"the-wanted-column-survives-a-short-line", "abcdef\nxy\nabcdefgh", "4ljj", "abcdef\nxy\nabcdefgh", 3, 5, "", ""},
    {"dollar-sticks-to-the-line-end", "abcdef\nxy\nabcdefgh", "$jj", "abcdef\nxy\nabcdefgh", 3, 8, "", ""},
    {"the-wanted-column-comes-back-up", "abcdef\nxy\nabcdefgh", "$jjk", "abcdef\nxy\nabcdefgh", 2, 2, "", ""},
    {"motions-do-nothing-in-an-empty-buffer", "", "w", "", 1, 1, "", ""},
    {"x-removes-the-character-under-the-caret", "hello", "x", "ello", 1, 1, "h", "v"},
    {"x-at-the-line-end-pulls-the-caret-back", "abc", "$x", "ab", 1, 2, "c", "v"},
    {"x-does-nothing-on-an-empty-line", "abc\n\ndef", "jx", "abc\n\ndef", 2, 1, "", ""},
    {"x-with-a-count", "abcd", "2x", "cd", 1, 1, "ab", "v"},
    {"x-with-a-count-clamps-to-the-line-end", "abc\ndef", "l3x", "a\ndef", 1, 1, "bc", "v"},
    {"dw-removes-the-word-and-its-blanks", "alpha beta", "dw", "beta", 1, 1, "alpha ", "v"},
    {"dw-stops-at-punctuation", "alpha, beta", "dw", ", beta", 1, 1, "alpha", "v"},
    {"dw-does-not-join-the-next-line", "alpha\nbeta", "dw", "\nbeta", 1, 1, "alpha", "v"},
    {"dw-on-the-last-word-of-a-line", "alpha beta\ngamma", "wdw", "alpha \ngamma", 1, 6, "beta", "v"},
    {"dw-on-an-empty-line-removes-the-newline", "abc\n\ndef", "jdw", "abc\ndef", 2, 1, "\n", "V"},
    {"dw-with-a-count", "alpha, beta", "2dw", "beta", 1, 1, "alpha, ", "v"},
    {"d-dollar-removes-to-the-line-end", "alpha beta", "ld$", "a", 1, 1, "lpha beta", "v"},
    {"d-zero-removes-to-the-line-start", "alpha beta", "$d0", "a", 1, 1, "alpha bet", "v"},
    {"dl-removes-the-character-under-the-caret", "abc", "$dl", "ab", 1, 2, "c", "v"},
    {"dh-does-nothing-at-the-line-start", "abc", "dh", "abc", 1, 1, "", ""},
    {"dh-with-a-count", "hello", "$d2h", "heo", 1, 3, "ll", "v"},
    {"db-removes-back-to-the-word-start", "hello world", "$db", "hello d", 1, 7, "worl", "v"},
    {"d-then-a-key-that-is-not-a-motion-is-dropped", "abc", "dx", "abc", 1, 1, "", ""},
    {"escape-drops-a-pending-operator", "abc", "d<Esc>x", "bc", 1, 1, "a", "v"},
    {"escape-drops-a-pending-count", "abc", "2<Esc>x", "bc", 1, 1, "a", "v"},
    {"dd-removes-the-line", "one\ntwo\nthree", "jdd", "one\nthree", 2, 1, "two\n", "V"},
    {"dd-on-the-last-line", "one\ntwo\nthree", "jjdd", "one\ntwo", 2, 1, "three\n", "V"},
    {"dd-goes-to-the-first-non-blank", "  one\n  two\n  three", "jdd", "  one\n  three", 2, 3, "  two\n", "V"},
    {"dd-with-a-count", "one\ntwo\nthree", "2dd", "three", 1, 1, "one\ntwo\n", "V"},
    {"dd-removes-the-only-line", "one", "dd", "", 1, 1, "one\n", "V"},
    {"dj-removes-the-line-below-too", "one\ntwo\nthree", "dj", "three", 1, 1, "one\ntwo\n", "V"},
    {"dk-removes-the-line-above-too", "one\ntwo\nthree", "jjdk", "one", 1, 1, "two\nthree\n", "V"},
    {"i-inserts-before-the-caret", "hello", "llix<Esc>", "hexllo", 1, 3, "", ""},
    {"a-inserts-after-the-caret", "hello", "llax<Esc>", "helxlo", 1, 4, "", ""},
    {"a-at-the-line-end-appends", "alpha", "$a!<Esc>", "alpha!", 1, 6, "", ""},
    {"capital-i-goes-to-the-first-non-blank", "  hello", "Ix<Esc>", "  xhello", 1, 3, "", ""},
    {"capital-i-after-a-tab", "\tindented", "Ix<Esc>", "\txindented", 1, 2, "", ""},
    {"capital-a-appends-at-the-line-end", "hello", "Ax<Esc>", "hellox", 1, 6, "", ""},
    {"escape-moves-one-left", "hello", "ihi<Esc>", "hihello", 1, 2, "", ""},
    {"escape-at-the-line-start-does-not-move", "hello", "i<Esc>", "hello", 1, 1, "", ""},
    {"enter-splits-the-line", "hello", "lli<CR><Esc>", "he\nllo", 2, 1, "", ""},
    {"enter-at-the-line-end-opens-a-line", "hello", "A<CR>world<Esc>", "hello\nworld", 2, 5, "", ""},
    {"backspace-joins-the-lines", "one\ntwo", "ji<BS>x<Esc>", "onextwo", 1, 4, "", ""},
    {"backspace-reaches-before-the-insert", "hello", "lllia<BS><BS>z<Esc>", "hezlo", 1, 3, "", ""},
    {"insert-into-an-empty-buffer", "", "ix<Esc>", "x", 1, 1, "", ""},
    {"undo-takes-back-one-insert", "hello", "ix<Esc>u", "hello", 1, 1, "", ""},
    {"redo-puts-the-insert-back", "hello", "ix<Esc>u<C-r>", "xhello", 1, 1, "", ""},
    {"undo-takes-back-one-x", "hello", "llxu", "hello", 1, 3, "l", "v"},
    {"undo-takes-back-one-line", "one\ntwo\nthree", "jddu", "one\ntwo\nthree", 2, 1, "two\n", "V"},
    {"japanese-x-removes-one-code-point", "あいう", "lx", "あう", 1, 4, "い", "v"},
    {"japanese-at-the-line-end-appends", "abcあ", "A!<Esc>", "abcあ!", 1, 7, "", ""},
    {"japanese-word-classes-split-the-line", "あいう、カタ abc", "www", "あいう、カタ abc", 1, 20, "", ""},
    {"japanese-dw-takes-one-class", "漢字かな", "dw", "かな", 1, 1, "漢字", "v"},
    {"japanese-x-at-the-line-end", "abcあ", "$x", "abc", 1, 3, "あ", "v"},
    {"japanese-dollar-is-the-last-code-point", "あいう abc", "$", "あいう abc", 1, 13, "", ""},
    {"w-crosses-digits-and-underscore", "abc 123_x", "ww", "abc 123_x", 1, 9, "", ""},
    {"w-on-letters-outside-the-class-table", "ＡＢ abc", "w", "ＡＢ abc", 1, 8, "", ""},
    {"b-over-the-blanks-at-the-buffer-start", "  abc", "wb", "  abc", 1, 1, "", ""},
    {"b-stops-on-an-empty-line", "abc\n\ndef", "jjb", "abc\n\ndef", 2, 1, "", ""},
    {"d-with-a-count-before-the-motion", "alpha beta gamma", "d3w", "", 1, 1, "alpha beta gamma", "v"},
    {"x-with-a-count-past-the-line", "abc", "9x", "", 1, 1, "abc", "v"},
    {"j-in-a-single-line-buffer", "abc", "lj", "abc", 1, 2, "", ""},
    {"dj-at-the-last-line-does-nothing", "one\ntwo\nthree", "jjdj", "one\ntwo\nthree", 3, 1, "", ""},
    {"dk-at-the-first-line-does-nothing", "one\ntwo", "dk", "one\ntwo", 1, 1, "", ""},
    {"dd-with-a-count-past-the-end", "one\ntwo", "j2dd", "one\ntwo", 2, 1, "", ""},
    {"undo-with-nothing-to-undo", "abc", "u", "abc", 1, 1, "", ""},
    {"redo-with-nothing-to-redo", "abc", "<C-r>", "abc", 1, 1, "", ""},
    {"dw-with-a-count-over-punctuation", "a.b c", "3dw", "c", 1, 1, "a.b ", "v"},
    {"capital-a-on-an-empty-line", "\nabc", "A0<Esc>", "0\nabc", 1, 1, "", ""},
    {"capital-i-on-an-empty-line", "\nabc", "I0<Esc>", "0\nabc", 1, 1, "", ""},
    {"b-with-a-count-over-an-empty-line", "abc\n\ndef", "jj2b", "abc\n\ndef", 1, 1, "", ""},
    {"d-with-a-count-on-both-sides", "alpha beta gamma delta", "2d3w", "", 1, 1, "alpha beta gamma delta", "v"},
    {"dd-with-a-count-on-both-sides", "a\nb\nc\nd\ne\nf\ng", "2d3d", "g", 1, 1, "a\nb\nc\nd\ne\nf\n", "V"},
    {"dd-with-a-count-clamps-to-the-last-line", "a\nb\nc", "5dd", "", 1, 1, "a\nb\nc\n", "V"},
    {"dd-with-a-count-clamps-from-the-middle", "a\nb\nc\nd\ne", "j5dd", "a", 1, 1, "b\nc\nd\ne\n", "V"},
    {"dj-with-a-count-clamps-to-the-last-line", "a\nb\nc", "5dj", "", 1, 1, "a\nb\nc\n", "V"},
    {"dk-with-a-count-clamps-to-the-first-line", "a\nb\nc", "jj5dk", "", 1, 1, "a\nb\nc\n", "V"},
    {"cw-takes-the-word-like-ce", "alpha beta gamma", "cwX<Esc>", "X beta gamma", 1, 1, "alpha", "v"},
    {"cw-from-the-middle-of-a-word", "alpha beta gamma", "llcwX<Esc>", "alX beta gamma", 1, 3, "pha", "v"},
    {"cw-on-the-last-character-of-a-word", "alpha beta gamma", "4lcwX<Esc>", "alphX beta gamma", 1, 5, "a", "v"},
    {"cw-on-blanks-behaves-like-dw", "alpha  beta", "5lcwX<Esc>", "alphaXbeta", 1, 6, "  ", "v"},
    {"cw-with-a-count", "alpha beta gamma", "2cwX<Esc>", "X gamma", 1, 1, "alpha beta", "v"},
    {"cw-at-the-end-of-the-last-word", "alpha beta", "$cwX<Esc>", "alpha betX", 1, 10, "a", "v"},
    {"ce-goes-on-to-the-next-word", "alpha beta gamma", "4lceX<Esc>", "alphX gamma", 1, 5, "a beta", "v"},
    {"ce-empties-the-only-word", "alpha", "ce<Esc>", "", 1, 1, "alpha", "v"},
    {"cc-keeps-the-line", "one\ntwo\nthree", "jccX<Esc>", "one\nX\nthree", 2, 1, "two\n", "V"},
    {"cc-drops-the-indent", "  one\ntwo", "ccX<Esc>", "X\ntwo", 1, 1, "  one\n", "V"},
    {"cc-on-the-only-line", "one", "ccX<Esc>", "X", 1, 1, "one\n", "V"},
    {"cc-with-a-count-leaves-one-line", "one\ntwo\nthree", "2ccX<Esc>", "X\nthree", 1, 1, "one\ntwo\n", "V"},
    {"cj-changes-two-lines", "one\ntwo\nthree", "cjX<Esc>", "X\nthree", 1, 1, "one\ntwo\n", "V"},
    {"ck-changes-the-line-above", "one\ntwo\nthree", "jjckX<Esc>", "one\nX", 2, 1, "two\nthree\n", "V"},
    {"c-zero-at-the-line-start-only-inserts", "alpha beta", "c0X<Esc>", "Xalpha beta", 1, 1, "", ""},
    {"cb-across-the-line-becomes-linewise", "  abc\ndef", "jcbX<Esc>", "X\ndef", 1, 1, "  abc\n", "V"},
    {"cb-inside-the-line", "alpha beta", "wcbX<Esc>", "Xbeta", 1, 1, "alpha ", "v"},
    {"cw-on-an-empty-line-becomes-linewise", "abc\n\ndef", "jcwX<Esc>", "abc\nX\ndef", 2, 1, "\n", "V"},
    {"yy-does-not-move-the-caret", "alpha beta", "llyy", "alpha beta", 1, 3, "alpha beta\n", "V"},
    {"yw-keeps-the-caret", "alpha beta", "yw", "alpha beta", 1, 1, "alpha ", "v"},
    {"yb-moves-to-the-range-start", "alpha beta", "$yb", "alpha beta", 1, 7, "bet", "v"},
    {"y-dollar-keeps-the-caret", "alpha beta", "ly$", "alpha beta", 1, 2, "lpha beta", "v"},
    {"yj-yanks-two-lines", "one\ntwo\nthree", "lyj", "one\ntwo\nthree", 1, 2, "one\ntwo\n", "V"},
    {"yk-moves-up-to-the-first-line", "one\ntwo\nthree", "jjlyk", "one\ntwo\nthree", 2, 2, "two\nthree\n", "V"},
    {"yk-clamps-the-column-on-a-short-line", "abcdefgh\nxy\nabcdefgh", "jj5lyk", "abcdefgh\nxy\nabcdefgh", 2, 2, "xy\nabcdefgh\n", "V"},
    {"yy-with-a-count-clamps-to-the-last-line", "a\nb\nc", "5yy", "a\nb\nc", 1, 1, "a\nb\nc\n", "V"},
    {"yy-with-a-count-on-the-last-line-does-nothing", "abc", "2Y", "abc", 1, 1, "", ""},
    {"y-with-a-count-on-both-sides", "a\nb\nc\nd\ne", "2y3y", "a\nb\nc\nd\ne", 1, 1, "a\nb\nc\nd\ne\n", "V"},
    {"yw-on-an-empty-line-is-linewise", "abc\n\ndef", "jyw", "abc\n\ndef", 2, 1, "\n", "V"},
    {"yb-across-the-line-is-linewise", "abc\ndef", "jyb", "abc\ndef", 1, 1, "abc\n", "V"},
    {"capital-d-removes-to-the-line-end", "alpha beta", "lD", "a", 1, 1, "lpha beta", "v"},
    {"capital-d-on-an-empty-line-does-nothing", "\nabc", "D", "\nabc", 1, 1, "", ""},
    {"capital-d-with-a-count-takes-the-next-line", "one\ntwo\nthree", "j2D", "one", 1, 1, "two\nthree\n", "V"},
    {"capital-d-with-a-count-on-the-last-line-does-nothing", "alpha beta", "2D", "alpha beta", 1, 1, "", ""},
    {"capital-c-changes-to-the-line-end", "alpha beta", "lCx<Esc>", "ax", 1, 2, "lpha beta", "v"},
    {"capital-y-yanks-the-line", "one\ntwo", "Y", "one\ntwo", 1, 1, "one\n", "V"},
    {"capital-y-with-a-count", "one\ntwo", "2Y", "one\ntwo", 1, 1, "one\ntwo\n", "V"},
    {"capital-y-on-the-last-line-with-a-count-does-nothing", "one\ntwo", "j2Y", "one\ntwo", 2, 1, "", ""},
    {"p-puts-the-character-after-the-caret", "abcdef", "ylp", "aabcdef", 1, 2, "a", "v"},
    {"p-at-the-line-end", "abcdef", "y2l$p", "abcdefab", 1, 8, "ab", "v"},
    {"p-with-a-count", "abcdef", "y2l3p", "aabababbcdef", 1, 7, "ab", "v"},
    {"capital-p-puts-before-the-caret", "abcdef", "yllP", "aabcdef", 1, 2, "a", "v"},
    {"p-puts-the-line-below", "one\ntwo\nthree", "yyjp", "one\ntwo\none\nthree", 3, 1, "one\n", "V"},
    {"capital-p-puts-the-line-above", "one\ntwo\nthree", "yyjP", "one\none\ntwo\nthree", 2, 1, "one\n", "V"},
    {"p-of-a-line-goes-to-the-first-non-blank", "  one\ntwo", "yyjp", "  one\ntwo\n  one", 3, 3, "  one\n", "V"},
    {"p-of-a-line-on-the-last-line", "one\ntwo", "jyyp", "one\ntwo\ntwo", 3, 1, "two\n", "V"},
    {"p-of-a-line-with-a-count", "one\ntwo\nthree", "yy2p", "one\none\none\ntwo\nthree", 2, 1, "one\n", "V"},
    {"capital-p-of-a-line-on-the-first-line", "one\ntwo\nthree", "yyP", "one\none\ntwo\nthree", 1, 1, "one\n", "V"},
    {"x-then-p-swaps-two-characters", "abc", "xp", "bac", 1, 2, "a", "v"},
    {"x-then-capital-p-puts-it-back", "abc", "xP", "abc", 1, 1, "a", "v"},
    {"x-at-the-line-end-then-p", "abc", "$xp", "abc", 1, 3, "c", "v"},
    {"dd-then-p-moves-the-line-down", "abc\ndef", "ddp", "def\nabc", 2, 1, "abc\n", "V"},
    {"dd-then-capital-p-puts-the-line-back", "abc\ndef", "ddP", "abc\ndef", 1, 1, "abc\n", "V"},
    {"dd-of-the-only-line-then-p", "one", "ddp", "\none", 2, 1, "one\n", "V"},
    {"dd-then-p-with-a-count", "one\ntwo\nthree", "dd2p", "two\none\none\nthree", 2, 1, "one\n", "V"},
    {"dj-then-p", "one\ntwo\nthree", "djp", "three\none\ntwo", 2, 1, "one\ntwo\n", "V"},
    {"dw-then-capital-p-puts-the-word-back", "alpha beta", "dwP", "alpha beta", 1, 6, "alpha ", "v"},
    {"dw-on-an-empty-line-then-p", "abc\n\ndef", "jdwp", "abc\ndef\n", 3, 1, "\n", "V"},
    {"y-dollar-then-p", "alpha", "y$p", "aalphalpha", 1, 6, "alpha", "v"},
    {"yb-then-capital-p", "alpha beta", "wybP", "alpha alpha beta", 1, 6, "alpha ", "v"},
    {"japanese-p-after-a-code-point", "あいう", "ylp", "ああいう", 1, 4, "あ", "v"},
    {"japanese-p-of-a-line", "あいう", "yyp", "あいう\nあいう", 2, 1, "あいう\n", "V"},
    {"e-goes-to-the-end-of-the-word", "alpha beta gamma", "e", "alpha beta gamma", 1, 5, "", ""},
    {"e-twice-crosses-the-blank", "alpha beta gamma", "ee", "alpha beta gamma", 1, 10, "", ""},
    {"e-stops-on-punctuation", "alpha, beta", "ee", "alpha, beta", 1, 6, "", ""},
    {"e-crosses-the-line", "alpha\nbeta", "$e", "alpha\nbeta", 2, 4, "", ""},
    {"e-with-a-count", "alpha beta", "2e", "alpha beta", 1, 10, "", ""},
    {"e-with-a-count-across-the-line", "alpha beta\ngamma", "3e", "alpha beta\ngamma", 2, 5, "", ""},
    {"e-skips-an-empty-line", "alpha\n\nbeta", "je", "alpha\n\nbeta", 3, 4, "", ""},
    {"japanese-e-stops-at-the-class-boundary", "あいう", "e", "あいう", 1, 7, "", ""},
    {"de-takes-the-word-inclusive", "alpha beta", "de", " beta", 1, 1, "alpha", "v"},
    {"de-on-the-last-character-takes-one", "alpha beta", "$de", "alpha bet", 1, 9, "a", "v"},
    {"de-with-a-count", "alpha beta gamma", "d2e", " gamma", 1, 1, "alpha beta", "v"},
    {"japanese-de-takes-one-class", "漢字かな", "de", "かな", 1, 1, "漢字", "v"},
    {"caret-goes-to-the-first-non-blank", "  alpha beta", "$^", "  alpha beta", 1, 3, "", ""},
    {"caret-on-a-line-of-blanks", "  \nabc", "^", "  \nabc", 1, 2, "", ""},
    {"caret-on-an-empty-line", "\nabc", "^", "\nabc", 1, 1, "", ""},
    {"d-caret-removes-back-to-the-first-non-blank", "  alpha beta", "$d^", "  a", 1, 3, "alpha bet", "v"},
    {"d-caret-on-an-empty-line-does-nothing", "\nabc", "d^", "\nabc", 1, 1, "", ""},
    {"home-goes-to-the-line-start", "  alpha", "$<Home>", "  alpha", 1, 1, "", ""},
    {"end-goes-to-the-last-character", "  alpha", "<End>", "  alpha", 1, 7, "", ""},
    {"d-with-end-removes-to-the-line-end", "  alpha", "d<End>", "", 1, 1, "  alpha", "v"},
    {"d-with-home-at-the-line-start-does-nothing", "abc", "d<Home>", "abc", 1, 1, "", ""},
    {"c-with-home-removes-to-the-line-start", "  abc", "$c<Home>X<Esc>", "Xc", 1, 1, "  ab", "v"},
    {"end-in-insert-goes-past-the-last-character", "hello", "lli<End>X<Esc>", "helloX", 1, 6, "", ""},
    {"home-in-insert-goes-to-the-line-start", "hello", "$i<Home>X<Esc>", "Xhello", 1, 1, "", ""},
    {"end-in-insert-on-an-empty-buffer", "", "i<End>X<Esc>", "X", 1, 1, "", ""},
    {"db-across-the-line-becomes-linewise", "abc\ndef", "jdb", "def", 1, 1, "abc\n", "V"},
    {"db-across-the-line-keeps-the-indent", "  abc\ndef", "jdb", "def", 1, 1, "  abc\n", "V"},
    {"db-inside-the-line-is-characterwise", "alpha beta", "wdb", "beta", 1, 1, "alpha ", "v"},
    {"db-across-the-line-outside-the-indent-stays-characterwise", "abc def\nghi", "jdb", "abc \nghi", 1, 4, "def", "v"},
    {"yb-across-the-line-outside-the-indent-stays-characterwise", "abc def\nghi", "jyb", "abc def\nghi", 1, 5, "def", "v"},
    {"de-across-the-line-with-text-after-it-stays-characterwise", "alpha\nbeta gamma", "$de", "alph gamma", 1, 5, "a\nbeta", "v"},
    {"de-across-the-line-outside-the-indent-stays-characterwise", "abc def\nghi", "$de", "abc de", 1, 6, "f\nghi", "v"},
    {"undo-takes-back-a-change", "hello", "cwbye<Esc>u", "hello", 1, 1, "hello", "v"},
    {"undo-takes-back-an-insert-with-a-backspace", "hello", "ia<BS>b<Esc>u", "hello", 1, 1, "", ""},
    {"japanese-cw-takes-one-class", "あいう、カタ", "cwX<Esc>", "X、カタ", 1, 1, "あいう", "v"},
    {"c-then-a-key-that-is-not-a-motion-is-dropped", "abc", "cx", "abc", 1, 1, "", ""},
    {"y-then-a-key-that-is-not-a-motion-is-dropped", "abc", "yx", "abc", 1, 1, "", ""},
    {"d-then-another-operator-is-dropped", "abc", "dy", "abc", 1, 1, "", ""},
    {"y-then-another-operator-is-dropped", "abc", "yd", "abc", 1, 1, "", ""},
    {"c-then-another-operator-is-dropped", "abc\ndef", "cdX<Esc>", "abc\ndef", 1, 1, "", ""},
    {"v-then-esc-changes-nothing", "alpha", "v<Esc>", "alpha", 1, 1, "", ""},
    {"v-then-v-leaves-visual", "alpha", "vlvx", "apha", 1, 2, "l", "v"},
    {"v-then-V-switches-to-linewise", "abc\ndef", "vVd", "def", 1, 1, "abc\n", "V"},
    {"V-then-v-switches-to-characterwise", "abc\ndef", "Vvd", "bc\ndef", 1, 1, "a", "v"},
    {"V-then-V-leaves-visual", "abc\ndef", "VVx", "bc\ndef", 1, 1, "a", "v"},
    {"a-count-before-v-is-ignored", "abcdef", "3vd", "def", 1, 1, "abc", "v"},
    {"V-then-esc-changes-nothing", "abc\ndef", "V<Esc>x", "bc\ndef", 1, 1, "a", "v"},
    {"v-d-removes-one-character", "alpha", "vd", "lpha", 1, 1, "a", "v"},
    {"v-x-is-the-same-as-d", "alpha", "vx", "lpha", 1, 1, "a", "v"},
    {"v-l-d-removes-two-characters", "alpha", "vld", "pha", 1, 1, "al", "v"},
    {"v-with-a-count-on-the-motion", "abcdefgh", "v3ld", "efgh", 1, 1, "abcd", "v"},
    {"v-y-yanks-the-selection", "alpha", "vly", "alpha", 1, 1, "al", "v"},
    {"v-c-changes-the-selection", "alpha", "vlcXY<Esc>", "XYpha", 1, 2, "al", "v"},
    {"v-h-selects-backwards", "alpha", "$vhd", "alp", 1, 3, "ha", "v"},
    {"v-dollar-d-takes-the-newline", "abc\ndef", "v$d", "def", 1, 1, "abc\n", "v"},
    {"v-dollar-y-takes-the-newline", "abc\ndef", "v$y", "abc\ndef", 1, 1, "abc\n", "v"},
    {"v-zero-d", "  abc", "$v0d", "", 1, 1, "  abc", "v"},
    {"v-caret-d", "  abc", "$v^d", "  ", 1, 2, "abc", "v"},
    {"v-w-d", "alpha beta", "vwd", "eta", 1, 1, "alpha b", "v"},
    {"v-w-at-the-last-word", "alpha beta", "wvwd", "alpha ", 1, 6, "beta", "v"},
    {"v-b-d", "alpha beta", "$vbd", "alpha ", 1, 6, "beta", "v"},
    {"v-e-d", "alpha beta", "ved", " beta", 1, 1, "alpha", "v"},
    {"v-home-d", "  abc", "$v<Home>d", "", 1, 1, "  abc", "v"},
    {"v-end-d", "abc\ndef", "v<End>d", "def", 1, 1, "abc\n", "v"},
    {"v-j-d-across-lines", "abc\ndef", "vjd", "ef", 1, 1, "abc\nd", "v"},
    {"v-j-y-across-lines", "abc\ndef", "vjy", "abc\ndef", 1, 1, "abc\nd", "v"},
    {"v-k-selects-upwards", "abc\ndef", "jlvkd", "af", 1, 2, "bc\nde", "v"},
    {"v-with-a-count-of-lines", "a\nb\nc\nd", "v2jd", "\nd", 1, 1, "a\nb\nc", "v"},
    {"v-j-keeps-the-wanted-column", "abcdef\nx\nabcdef", "3lvjjd", "abcef", 1, 4, "def\nx\nabcd", "v"},
    {"v-on-an-empty-line-d", "abc\n\ndef", "jvd", "abc\ndef", 2, 1, "\n", "v"},
    {"v-on-an-empty-line-y", "abc\n\ndef", "jvy", "abc\n\ndef", 2, 1, "\n", "v"},
    {"v-japanese-d", "あいうえお", "vld", "うえお", 1, 1, "あい", "v"},
    {"v-japanese-y", "あいうえお", "vlly", "あいうえお", 1, 1, "あいう", "v"},
    {"v-c-across-lines", "abc\ndef", "vjcX<Esc>", "Xef", 1, 1, "abc\nd", "v"},
    {"v-o-keeps-the-same-range", "abcdef", "3lvhhod", "aef", 1, 2, "bcd", "v"},
    {"v-o-then-a-motion-moves-the-other-end", "abcdef", "3lvhhohd", "adef", 1, 2, "bc", "v"},
    {"V-o-then-j-extends-the-other-end", "a\nb\nc\nd\ne", "2jVkojd", "a\ne", 2, 1, "b\nc\nd\n", "V"},
    {"V-d-removes-the-line", "abc\ndef\nghi", "jVd", "abc\nghi", 2, 1, "def\n", "V"},
    {"V-d-on-the-last-line", "abc\ndef", "jVd", "abc", 1, 1, "def\n", "V"},
    {"V-j-d-removes-two-lines", "abc\ndef\nghi", "Vjd", "ghi", 1, 1, "abc\ndef\n", "V"},
    {"V-with-a-count-of-lines", "a\nb\nc\nd", "V2jd", "d", 1, 1, "a\nb\nc\n", "V"},
    {"V-y-yanks-a-line", "abc\ndef", "Vy", "abc\ndef", 1, 1, "abc\n", "V"},
    {"V-j-y-yanks-two-lines", "abc\ndef", "Vjy", "abc\ndef", 1, 1, "abc\ndef\n", "V"},
    {"V-c-changes-the-line", "abc\ndef", "VcX<Esc>", "X\ndef", 1, 1, "abc\n", "V"},
    {"V-j-c-changes-two-lines", "abc\ndef\nghi", "VjcX<Esc>", "X\nghi", 1, 1, "abc\ndef\n", "V"},
    {"V-dollar-keeps-the-line-range", "abc\ndef", "V$d", "def", 1, 1, "abc\n", "V"},
    {"V-zero-keeps-the-line-range", "  abc\ndef", "V0d", "def", 1, 1, "  abc\n", "V"},
    {"V-x-removes-the-line", "abc\ndef", "Vx", "def", 1, 1, "abc\n", "V"},
    {"V-k-selects-upwards", "abc\ndef\nghi", "jjVkd", "abc", 1, 1, "def\nghi\n", "V"},
    {"V-on-an-empty-line", "abc\n\ndef", "jVd", "abc\ndef", 2, 1, "\n", "V"},
    {"V-indented-line-keeps-the-indent-in-the-register", "abc\n  def", "jVy", "abc\n  def", 2, 1, "  def\n", "V"},
    {"V-y-then-p-puts-a-whole-line", "abc\ndef", "Vyp", "abc\nabc\ndef", 2, 1, "abc\n", "V"},
    {"v-y-then-p-puts-characters", "abcdef", "vlyp", "aabbcdef", 1, 3, "ab", "v"},
    {"v-d-then-undo", "alpha", "vlldu", "alpha", 1, 1, "alp", "v"},
    {"V-d-then-undo", "abc\ndef", "Vdu", "abc\ndef", 1, 1, "abc\n", "V"},
    {"v-l-reaches-the-line-end", "abc\ndef", "llvld", "abdef", 1, 3, "c\n", "v"},
    {"v-l-with-a-big-count-stops-at-the-line-end", "abc\ndef", "v9ld", "def", 1, 1, "abc\n", "v"},
    {"v-dollar-then-j-keeps-the-line-end", "abc\ndef", "v$jd", "", 1, 1, "abc\ndef", "v"},
    {"v-e-at-the-last-word", "alpha beta", "wved", "alpha ", 1, 6, "beta", "v"},
    {"a-count-before-V-selects-lines", "a\nb\nc\nd", "3Vd", "d", 1, 1, "a\nb\nc\n", "V"},
    {"v-does-not-take-the-whole-line-like-d-does", "  abc\n   ", "vjd", "  ", 1, 1, "  abc\n ", "v"},
}};
} // namespace nenenib::tests
// clang-format on
