// clang-format off
// 生成物。手で編集しない。python eng/vim-oracle.py --regenerate（Vim 9.1）
// oracle: C:\Program Files\Vim\vim91\vim.exe — VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  3 2024 23:53:58)
// 既定の設定（ADR 0012 の決定 8）: set nocompatible / set backspace=indent,eol,start
// fixtures.json: sha256 15758fd401ff69391128aa748ceaf91a7441caed9553e8b35cde8ac07736ac48 / 87 fixtures
#pragma once

#include "VimFixture.hpp"

#include <array>

namespace nenenib::tests
{
constexpr std::array<VimFixture, 87> vim_fixtures{{
    {"h-at-the-line-start-stays", "alpha", "h", "alpha", 1, 1, ""},
    {"h-with-a-count", "alpha", "$3h", "alpha", 1, 2, ""},
    {"l-does-not-pass-the-last-character", "abc", "lll", "abc", 1, 3, ""},
    {"l-with-a-count-clamps", "hello", "5l", "hello", 1, 5, ""},
    {"zero-goes-to-the-line-start", "  abc", "$0", "  abc", 1, 1, ""},
    {"dollar-goes-to-the-last-character", "  abc", "$", "  abc", 1, 5, ""},
    {"w-crosses-punctuation", "alpha, beta; gamma", "www", "alpha, beta; gamma", 1, 12, ""},
    {"w-crosses-the-line", "alpha beta\ngamma", "ww", "alpha beta\ngamma", 2, 1, ""},
    {"w-stops-on-the-last-word", "alpha beta", "ww", "alpha beta", 1, 10, ""},
    {"w-stops-on-an-empty-line", "abc\n\ndef", "w", "abc\n\ndef", 2, 1, ""},
    {"w-with-a-count", "one two three", "2w", "one two three", 1, 9, ""},
    {"b-crosses-punctuation", "alpha, beta", "$bb", "alpha, beta", 1, 6, ""},
    {"b-crosses-the-line", "abc\ndef", "jb", "abc\ndef", 1, 1, ""},
    {"b-at-the-start-of-the-buffer-stays", "abc", "b", "abc", 1, 1, ""},
    {"b-with-a-count", "one two three", "$2b", "one two three", 1, 5, ""},
    {"j-with-a-count-clamps-to-the-last-line", "one\ntwo", "3j", "one\ntwo", 2, 1, ""},
    {"k-with-a-count-clamps-to-the-first-line", "one\ntwo", "j3k", "one\ntwo", 1, 1, ""},
    {"the-wanted-column-survives-a-short-line", "abcdef\nxy\nabcdefgh", "4ljj", "abcdef\nxy\nabcdefgh", 3, 5, ""},
    {"dollar-sticks-to-the-line-end", "abcdef\nxy\nabcdefgh", "$jj", "abcdef\nxy\nabcdefgh", 3, 8, ""},
    {"the-wanted-column-comes-back-up", "abcdef\nxy\nabcdefgh", "$jjk", "abcdef\nxy\nabcdefgh", 2, 2, ""},
    {"motions-do-nothing-in-an-empty-buffer", "", "w", "", 1, 1, ""},
    {"x-removes-the-character-under-the-caret", "hello", "x", "ello", 1, 1, "h"},
    {"x-at-the-line-end-pulls-the-caret-back", "abc", "$x", "ab", 1, 2, "c"},
    {"x-does-nothing-on-an-empty-line", "abc\n\ndef", "jx", "abc\n\ndef", 2, 1, ""},
    {"x-with-a-count", "abcd", "2x", "cd", 1, 1, "ab"},
    {"x-with-a-count-clamps-to-the-line-end", "abc\ndef", "l3x", "a\ndef", 1, 1, "bc"},
    {"dw-removes-the-word-and-its-blanks", "alpha beta", "dw", "beta", 1, 1, "alpha "},
    {"dw-stops-at-punctuation", "alpha, beta", "dw", ", beta", 1, 1, "alpha"},
    {"dw-does-not-join-the-next-line", "alpha\nbeta", "dw", "\nbeta", 1, 1, "alpha"},
    {"dw-on-the-last-word-of-a-line", "alpha beta\ngamma", "wdw", "alpha \ngamma", 1, 6, "beta"},
    {"dw-on-an-empty-line-removes-the-newline", "abc\n\ndef", "jdw", "abc\ndef", 2, 1, "\n"},
    {"dw-with-a-count", "alpha, beta", "2dw", "beta", 1, 1, "alpha, "},
    {"d-dollar-removes-to-the-line-end", "alpha beta", "ld$", "a", 1, 1, "lpha beta"},
    {"d-zero-removes-to-the-line-start", "alpha beta", "$d0", "a", 1, 1, "alpha bet"},
    {"dl-removes-the-character-under-the-caret", "abc", "$dl", "ab", 1, 2, "c"},
    {"dh-does-nothing-at-the-line-start", "abc", "dh", "abc", 1, 1, ""},
    {"dh-with-a-count", "hello", "$d2h", "heo", 1, 3, "ll"},
    {"db-removes-back-to-the-word-start", "hello world", "$db", "hello d", 1, 7, "worl"},
    {"d-then-a-key-that-is-not-a-motion-is-dropped", "abc", "dx", "abc", 1, 1, ""},
    {"escape-drops-a-pending-operator", "abc", "d<Esc>x", "bc", 1, 1, "a"},
    {"escape-drops-a-pending-count", "abc", "2<Esc>x", "bc", 1, 1, "a"},
    {"dd-removes-the-line", "one\ntwo\nthree", "jdd", "one\nthree", 2, 1, "two\n"},
    {"dd-on-the-last-line", "one\ntwo\nthree", "jjdd", "one\ntwo", 2, 1, "three\n"},
    {"dd-goes-to-the-first-non-blank", "  one\n  two\n  three", "jdd", "  one\n  three", 2, 3, "  two\n"},
    {"dd-with-a-count", "one\ntwo\nthree", "2dd", "three", 1, 1, "one\ntwo\n"},
    {"dd-removes-the-only-line", "one", "dd", "", 1, 1, "one\n"},
    {"dj-removes-the-line-below-too", "one\ntwo\nthree", "dj", "three", 1, 1, "one\ntwo\n"},
    {"dk-removes-the-line-above-too", "one\ntwo\nthree", "jjdk", "one", 1, 1, "two\nthree\n"},
    {"i-inserts-before-the-caret", "hello", "llix<Esc>", "hexllo", 1, 3, ""},
    {"a-inserts-after-the-caret", "hello", "llax<Esc>", "helxlo", 1, 4, ""},
    {"a-at-the-line-end-appends", "alpha", "$a!<Esc>", "alpha!", 1, 6, ""},
    {"capital-i-goes-to-the-first-non-blank", "  hello", "Ix<Esc>", "  xhello", 1, 3, ""},
    {"capital-i-after-a-tab", "\tindented", "Ix<Esc>", "\txindented", 1, 2, ""},
    {"capital-a-appends-at-the-line-end", "hello", "Ax<Esc>", "hellox", 1, 6, ""},
    {"escape-moves-one-left", "hello", "ihi<Esc>", "hihello", 1, 2, ""},
    {"escape-at-the-line-start-does-not-move", "hello", "i<Esc>", "hello", 1, 1, ""},
    {"enter-splits-the-line", "hello", "lli<CR><Esc>", "he\nllo", 2, 1, ""},
    {"enter-at-the-line-end-opens-a-line", "hello", "A<CR>world<Esc>", "hello\nworld", 2, 5, ""},
    {"backspace-joins-the-lines", "one\ntwo", "ji<BS>x<Esc>", "onextwo", 1, 4, ""},
    {"backspace-reaches-before-the-insert", "hello", "lllia<BS><BS>z<Esc>", "hezlo", 1, 3, ""},
    {"insert-into-an-empty-buffer", "", "ix<Esc>", "x", 1, 1, ""},
    {"undo-takes-back-one-insert", "hello", "ix<Esc>u", "hello", 1, 1, ""},
    {"redo-puts-the-insert-back", "hello", "ix<Esc>u<C-r>", "xhello", 1, 1, ""},
    {"undo-takes-back-one-x", "hello", "llxu", "hello", 1, 3, "l"},
    {"undo-takes-back-one-line", "one\ntwo\nthree", "jddu", "one\ntwo\nthree", 2, 1, "two\n"},
    {"japanese-x-removes-one-code-point", "あいう", "lx", "あう", 1, 4, "い"},
    {"japanese-at-the-line-end-appends", "abcあ", "A!<Esc>", "abcあ!", 1, 7, ""},
    {"japanese-word-classes-split-the-line", "あいう、カタ abc", "www", "あいう、カタ abc", 1, 20, ""},
    {"japanese-dw-takes-one-class", "漢字かな", "dw", "かな", 1, 1, "漢字"},
    {"japanese-x-at-the-line-end", "abcあ", "$x", "abc", 1, 3, "あ"},
    {"japanese-dollar-is-the-last-code-point", "あいう abc", "$", "あいう abc", 1, 13, ""},
    {"w-crosses-digits-and-underscore", "abc 123_x", "ww", "abc 123_x", 1, 9, ""},
    {"w-on-letters-outside-the-class-table", "ＡＢ abc", "w", "ＡＢ abc", 1, 8, ""},
    {"b-over-the-blanks-at-the-buffer-start", "  abc", "wb", "  abc", 1, 1, ""},
    {"b-stops-on-an-empty-line", "abc\n\ndef", "jjb", "abc\n\ndef", 2, 1, ""},
    {"d-with-a-count-before-the-motion", "alpha beta gamma", "d3w", "", 1, 1, "alpha beta gamma"},
    {"x-with-a-count-past-the-line", "abc", "9x", "", 1, 1, "abc"},
    {"j-in-a-single-line-buffer", "abc", "lj", "abc", 1, 2, ""},
    {"dj-at-the-last-line-does-nothing", "one\ntwo\nthree", "jjdj", "one\ntwo\nthree", 3, 1, ""},
    {"dk-at-the-first-line-does-nothing", "one\ntwo", "dk", "one\ntwo", 1, 1, ""},
    {"dd-with-a-count-past-the-end", "one\ntwo", "j2dd", "one\ntwo", 2, 1, ""},
    {"undo-with-nothing-to-undo", "abc", "u", "abc", 1, 1, ""},
    {"redo-with-nothing-to-redo", "abc", "<C-r>", "abc", 1, 1, ""},
    {"dw-with-a-count-over-punctuation", "a.b c", "3dw", "c", 1, 1, "a.b "},
    {"capital-a-on-an-empty-line", "\nabc", "A0<Esc>", "0\nabc", 1, 1, ""},
    {"capital-i-on-an-empty-line", "\nabc", "I0<Esc>", "0\nabc", 1, 1, ""},
    {"b-with-a-count-over-an-empty-line", "abc\n\ndef", "jj2b", "abc\n\ndef", 1, 1, ""},
}};
} // namespace nenenib::tests
// clang-format on
